//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieReleases.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public Movie()
        {
            this.WatchListItem = new HashSet<WatchListItem>();
        }
    
        public int Id { get; set; }
        public string Imdb { get; set; }
        public string Plot { get; set; }
        public string Duration { get; set; }
        public string PosterUrl { get; set; }
        public string Title { get; set; }
        public string Year { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public MovieReleases.Core.Movies.MovieType MovieType { get; set; }
    
        public virtual ICollection<WatchListItem> WatchListItem { get; set; }
    }
}
