//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieReleases.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Friends = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public string Username { get; set; }
    
        public virtual Watchlist Watchlist { get; set; }
        public virtual ICollection<User> Friends { get; set; }
    }
}
