//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieReleases.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class WatchListItem
    {
        public int Id { get; set; }
        public bool Watched { get; set; }
        public bool InPosession { get; set; }
        public int WatchlistId { get; set; }
    
        public virtual Watchlist Watchlist { get; set; }
        public virtual Movie Movie { get; set; }
    }
}
